services:
  postgres:
    image: postgres:15-alpine
    container_name: judge-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: judge_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - judge-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  judge-worker:
    build: ./CodeExecutor
    deploy:
      replicas: 5
    restart: always 
    environment:
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
    user: root
    networks:
      - judge-net
    privileged: true
    volumes:
      - ./judge_data:/app/judge_data
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - judge-net
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 10s
      retries: 5

networks:
  judge-net:

volumes:
  postgres_data: